-- MySQL Script generated by MySQL Workbench
-- Sun Mar 8 18:17:07 2015
-- Model: New Model Version: 1.0
-- MySQL Workbench Forward Engineering
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';
-- -----------------------------------------------------
-- Schema course_management
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `course_management` ;
-- -----------------------------------------------------
-- Schema course_management
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `course_management` DEFAULT CHARACTER SET
utf8 COLLATE utf8_general_ci ;
USE `course_management` ;
-- -----------------------------------------------------
-- Table `course_management`.`teacher`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `course_management`.`teacher` ;
CREATE TABLE IF NOT EXISTS `course_management`.`teacher` (
`id` INT NOT NULL AUTO_INCREMENT,
`first_name` VARCHAR(45) NOT NULL,
`last_name` VARCHAR(45) NULL,
`designation` VARCHAR(45) NOT NULL,
PRIMARY KEY (`id`))
ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `course_management`.`course`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `course_management`.`course` ;
CREATE TABLE IF NOT EXISTS `course_management`.`course` (
`id` INT NOT NULL AUTO_INCREMENT,
`name` VARCHAR(45) NOT NULL,
`credits` INT NOT NULL,
`teacher_id` INT NULL,
PRIMARY KEY (`id`),
INDEX `fk_course_teacher_idx` (`teacher_id` ASC),
CONSTRAINT `fk_course_teacher`
FOREIGN KEY (`teacher_id`)
REFERENCES `course_management`.`teacher` (`id`)
ON DELETE NO ACTION
ON UPDATE NO ACTION)
ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `course_management`.`student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `course_management`.`student` ;
CREATE TABLE IF NOT EXISTS `course_management`.`student` (
`id` INT NOT NULL AUTO_INCREMENT,
`first_name` VARCHAR(45) NOT NULL,
`last_name` VARCHAR(45) NULL,
`enrolled_since` MEDIUMTEXT NOT NULL,
PRIMARY KEY (`id`))
ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `course_management`.`course_student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `course_management`.`course_student` ;
CREATE TABLE IF NOT EXISTS `course_management`.`course_student` (
`course_id` INT NOT NULL,
`student_id` INT NOT NULL,
PRIMARY KEY (`course_id`, `student_id`),
INDEX `fk_course_has_student_student1_idx` (`student_id` ASC),
INDEX `fk_course_has_student_course1_idx` (`course_id` ASC),
CONSTRAINT `fk_course_has_student_course1`
FOREIGN KEY (`course_id`)
REFERENCES `course_management`.`course` (`id`)
ON DELETE NO ACTION
ON UPDATE NO ACTION,
CONSTRAINT `fk_course_has_student_student1`
FOREIGN KEY (`student_id`)
REFERENCES `course_management`.`student` (`id`)
ON DELETE NO ACTION
ON UPDATE NO ACTION)
ENGINE = InnoDB;
SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;